### ISSUE TITLE
ELAN tier structure

### ISSUE THREAD

**Issue by meehkal** [langdoc/FRechdoc#1]
The ELAN tier structure needs to be documented. This is urgent!

**Comment by meehkal** [comment]
The files are added but need to be finished.

**Comment by nikopartanen** [comment]
Can this issue be considered ready or are there parts which are still undocumented?

We have templates:

https://github.com/langdoc/FRechdoc/tree/master/etf

Relatively comprehensive documentation:

https://github.com/langdoc/FRechdoc/wiki/ELAN-tiers

Some test template to store individual study / experiment related tiers:

https://github.com/langdoc/FRechdoc/wiki/Individual-tiers

This [issue](https://github.com/langdoc/FRechdoc/issues/6) connects here as well.

Next related issue could be to harmonize the conventions to all ELAN files in different projects, but for this the structure has to be perfectly clear.
